"""
Spec-Guided Test Cases for is_prime (Exercise 3 Part 2)
"""

def is_prime(n: int) -> bool:
    """Return true if a given number is prime, and false otherwise."""
    if n < 2:
        return False
    for k in range(2, n):
        if n % k == 0:
            return False
    return True


# SPEC-GUIDED TESTS (generated by ChatGPT 5.1)

def test_spec_1_numbers_less_than_two():
    # Test for Specification 1:
    # Numbers less than 2 are not prime
    test_values = [-10, -1, 0, 1]

    for n in test_values:
        res = is_prime(n)
        # Spec 1: (n >= 2) or (not res)
        assert (n >= 2) or (not res), \
            f"Spec 1 violated for n={n}: numbers < 2 must not be classified as prime"


def test_spec_2_two_is_prime():
    # Test for Specification 2:
    # Number 2 is prime
    n = 2
    res = is_prime(n)

    # Spec 2: (n != 2) or res
    assert (n != 2) or res, "Spec 2 violated for n=2: 2 must be classified as prime"

    # Optional oracle check (not from the spec, but reasonable):
    assert res is True, "2 should be prime"


def test_spec_3_even_numbers_greater_than_two():
    # Test for Specification 3:
    # Even numbers > 2 are not prime
    test_values = [4, 6, 10, 100, 102]

    for n in test_values:
        res = is_prime(n)
        # Spec 3: (n <= 2) or (n % 2 != 0) or (not res)
        assert (n <= 2) or (n % 2 != 0) or (not res), \
            f"Spec 3 violated for n={n}: even numbers > 2 must not be prime"

        # Oracle check: these are known composites
        assert res is False, f"{n} is even and > 2, so it should not be prime"


def test_spec_4_prime_numbers_have_no_divisors():
    # Test for Specification 4:
    # If res is True, n has no divisors in [2, n-1]
    prime_candidates = [2, 3, 5, 7, 11, 29]

    for n in prime_candidates:
        res = is_prime(n)

        # Spec 4: (not res) or all(n % d != 0 for d in range(2, n))
        assert (not res) or all(n % d != 0 for d in range(2, n)), \
            f"Spec 4 violated for n={n}: if res is True, n must not be divisible by any d in [2, n-1]"

        # Oracle check to ensure correctness for standard primes:
        assert res is True, f"{n} is prime and should be classified as such"


def test_spec_5_composite_numbers_have_divisors():
    # Test for Specification 5:
    # If res is False and n >= 2, then n has some divisor in [2, n-1]
    composite_values = [4, 6, 9, 15, 21, 100]

    for n in composite_values:
        res = is_prime(n)

        # Spec 5: res or (n < 2) or any(n % d == 0 for d in range(2, n))
        assert res or (n < 2) or any(n % d == 0 for d in range(2, n)), \
            f"Spec 5 violated for n={n}: if res is False and n >= 2, there must exist a divisor in [2, n-1]"

        # Oracle check: these are known composites, so res should be False
        assert res is False, f"{n} is composite and should not be classified as prime"


def test_spec_edge_negative_and_large_values():
    # Spec-guided edge cases:
    #  - Negative numbers (Spec 1)
    #  - Larger prime and composite (Specs 3–5)
    test_values = [-5, -2, 0, 1, 97, 99]  # 97 is prime, 99 is composite

    for n in test_values:
        res = is_prime(n)

        # Spec 1: Numbers < 2 are not prime
        assert (n >= 2) or (not res), \
            f"Spec 1 violated for edge n={n}"

        # For n >= 2, apply Specs 4 and 5 as appropriate
        if n >= 2:
            # Spec 4: If res is True, n has no divisors in [2, n-1]
            assert (not res) or all(n % d != 0 for d in range(2, n)), \
                f"Spec 4 violated for n={n}"

            # Spec 5: If res is False and n >= 2, then n has some divisor in [2, n-1]
            assert res or any(n % d == 0 for d in range(2, n)), \
                f"Spec 5 violated for n={n}"

        # Oracle checks for the specific cases:
        if n == 97:
            assert res is True, "97 is prime and should be classified as such"
        if n == 99:
            assert res is False, "99 is composite and should not be prime"

