"""
Spec-Guided Test Cases for make_palindrome (Exercise 3 Part 2)
"""

def is_palindrome(string: str) -> bool:
    """Test if given string is a palindrome"""
    return string == string[::-1]


def make_palindrome(string: str) -> str:
    """Find the shortest palindrome that begins with a supplied string."""
    if not string:
        return ''
    
    beginning_of_suffix = 0
    
    while not is_palindrome(string[beginning_of_suffix:]):
        beginning_of_suffix += 1
    
    return string + string[:beginning_of_suffix][::-1]


# SPEC-GUIDED TESTS (generated by ChatGPT 5.1)

def test_spec_1_empty_string():
    # Test for Specification 1: Empty string handling
    string = ""
    res = make_palindrome(string)

    # Spec 1
    assert (string != "") or (res == ""), \
        "Spec 1 violated: If the input string is empty, the result must also be an empty string"

    # Specs 2–5 should still hold even for empty input
    # Spec 2: result is palindrome
    assert res == res[::-1], "Spec 2 violated for empty input"

    # Spec 3: result starts with input
    assert res.startswith(string), "Spec 3 violated for empty input"

    # Spec 4: length constraints
    assert (string == "" and len(res) == 0) or \
           (string != "" and len(string) <= len(res) <= 2 * len(string)), \
        "Spec 4 violated for empty input"

    # Spec 5: minimality (vacuously true, but we still check)
    assert all(
        not (prefix.startswith(string) and prefix == prefix[::-1])
        for prefix in (res[:k] for k in range(len(string), len(res)))
    ), "Spec 5 violated for empty input"


def test_spec_2_result_is_palindrome_for_various_inputs():
    # Test for Specification 2: The result must be a palindrome
    test_strings = ["a", "ab", "race", "abba", "abc"]

    for string in test_strings:
        res = make_palindrome(string)

        # Spec 2: res must be a palindrome
        assert res == res[::-1], \
            f"Spec 2 violated for string={string!r}: result {res!r} is not a palindrome"

        # Sanity: still starts with original string (Spec 3)
        assert res.startswith(string), \
            f"Spec 3 violated for string={string!r}: result does not start with input"


def test_spec_3_result_starts_with_input():
    # Test for Specification 3: The result must start with the original string
    test_strings = ["a", "ab", "aba", "hello", "xyz"]

    for string in test_strings:
        res = make_palindrome(string)

        # Spec 3
        assert res.startswith(string), \
            f"Spec 3 violated for string={string!r}: result {res!r} does not begin with the original string"

        # Also check palindromicity for these cases (Spec 2)
        assert res == res[::-1], \
            f"Spec 2 violated for string={string!r}: result {res!r} is not a palindrome"


def test_spec_4_length_constraints():
    # Test for Specification 4: Length constraints relative to input
    test_strings = ["a", "ab", "aa", "aba", "abc", "abcd", "race"]

    for string in test_strings:
        res = make_palindrome(string)

        # Spec 4
        assert (string == "" and len(res) == 0) or \
               (string != "" and len(string) <= len(res) <= 2 * len(string)), \
            f"Spec 4 violated for string={string!r}: len(res)={len(res)}, len(string)={len(string)}"

        # Keep Spec 2 and 3 enforced here as well
        assert res == res[::-1], \
            f"Spec 2 violated for string={string!r}"
        assert res.startswith(string), \
            f"Spec 3 violated for string={string!r}"


def test_spec_5_minimality_property():
    # Test for Specification 5: Minimality of the palindrome
    # Using a variety of inputs where we expect non-trivial extensions
    test_strings = [
        "a",      # already palindrome
        "aa",     # already palindrome
        "ab",     # needs 1 char appended => "aba"
        "aba",    # already palindrome
        "abab",   # should add minimal suffix
        "abcd",   # longer non-palindrome
    ]

    for string in test_strings:
        res = make_palindrome(string)

        # Re-assert earlier specs (2–4)
        assert res == res[::-1], "Spec 2 violated in minimality test"
        assert res.startswith(string), "Spec 3 violated in minimality test"
        assert (string == "" and len(res) == 0) or \
               (string != "" and len(string) <= len(res) <= 2 * len(string)), \
            "Spec 4 violated in minimality test"

        # Spec 5: No shorter prefix of res is a palindrome starting with string
        assert all(
            not (prefix.startswith(string) and prefix == prefix[::-1])
            for prefix in (res[:k] for k in range(len(string), len(res)))
        ), (
            f"Spec 5 violated for string={string!r}: "
            "Found a shorter palindromic prefix starting with the input"
        )


def test_spec_edge_cases_various_strings():
    # Spec-guided edge cases:
    #  - Single character
    #  - Repeated characters
    #  - Mixed characters
    #  - Already palindrome and clearly non-palindrome
    test_strings = [
        "z",          # single char
        "zzzz",       # all same char, already palindrome
        "abba",       # even-length palindrome
        "abcba",      # odd-length palindrome
        "abca",       # near palindrome
        "aaaaab",     # repeated chars with one different at end
    ]

    for string in test_strings:
        res = make_palindrome(string)

        # Spec 1 (not directly relevant here, but harmless)
        assert (string != "") or (res == ""), "Spec 1 violated in edge tests"

        # Spec 2
        assert res == res[::-1], \
            f"Spec 2 violated for edge string={string!r}"

        # Spec 3
        assert res.startswith(string), \
            f"Spec 3 violated for edge string={string!r}"

        # Spec 4
        assert (string == "" and len(res) == 0) or \
               (string != "" and len(string) <= len(res) <= 2 * len(string)), \
            f"Spec 4 violated for edge string={string!r}"

        # Spec 5
        assert all(
            not (prefix.startswith(string) and prefix == prefix[::-1])
            for prefix in (res[:k] for k in range(len(string), len(res)))
        ), (
            f"Spec 5 violated for edge string={string!r}: "
            "Found a shorter palindromic prefix starting with the input"
        )

